version: '3.8'

services:
  auth-service:
    image: auth:latest
    ports:
      - "4001:4000"
    environment:
      JWT_SECRET: supersecretkey
      DB_HOST: db-auth

  user-service:
    image: users:latest
    ports:
      - "4002:4000"
    environment:
      DB_HOST: db-users

  order-service:
    image: orders:latest
    ports:
      - "4003:4000"
    environment:
      RABBITMQ_HOST: queue

  db-auth:
    image: mongo:6.0

  db-users:
    image: mongo:6.0

volumes:
  auth_data:
  user_data:
